version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ./Mysql_Data:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "administrator"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "usuario"
      MYSQL_ROOT_PASSWORD: "root"
    tty: true
